name: CI
on: [push]
jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      NEXT_TELEMETRY_DISABLED: 1
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm install --production=false
    - name: Run typechecker
      run: npm run typecheck
    - name: Run linter
      run: npm run lint
    - name: Run tests
      run: npm run test-ci
  build:
    runs-on: ubuntu-latest
    env:
      NEXT_TELEMETRY_DISABLED: 1
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm install --production=false
    - name: Run production build
      run: npm run build
